language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - (cd vanilla-python-ci/unittests/ && python testquad.py)
  - (cd vanilla-python-ci/ && coverage run main.py)
  - 'bash <(curl -s https://codecov.io/bash)'
