language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - (cd vanilla-python-ci/unittests/ && coverage run testquad.py)
after_success:
  - codecov -t e951cd8b-d4d2-46e3-adc8-83cca9ab08ac
